### ISSUE TITLE
ValueError: Not all keys present in data! Needs mix_magnitude

### ISSUE THREAD

**Issue by jgussman** [nussl/nussl#165] opened 2020-08-04 17:24 UTC
Hiya,
I'm going through the tutorial on https://nussl.github.io/docs/tutorials/training.html so I can train my deep learning model. However, I ran into a problem. After a few minutes of passing my data into a training the model that is identical to the first model in that tutorial I get the error "ValueError: Not all keys present in data! Needs mix_magnitude". I checked and made sure all my data have 'mix_magnitudes' keys. I can't pinpoint where this problem is coming from. Any help would be much appreciated. 
Thank you,
Jude

**Comment by ethman** [comment] 2020-08-04 18:40
Hello Jude,

How are you loading your data into nussl? Are you using one of the dataset loaders (https://nussl.github.io/docs/datasets.html)? That should take care of adding the keys you need. If you are using that, can you provide some code or a notebook that reproduces this problem so we can figure out the issue?

Thanks,
-Ethan

**Comment by jgussman** [comment] 2020-08-04 18:46
Yes I am. 
`import os
import json
import logging
import copy
import tempfile
import glob
import time
import shutil
from concurrent.futures import ThreadPoolExecutor

import torch
import numpy as np
import matplotlib.pyplot as plt
import tqdm

import nussl

#According to https://nussl.github.io/docs/tutorials/datasets.html#BaseDataset making this class is helpful for organization
#This CONSINEDataSet is basically a complete rip off of https://github.com/nussl/nussl/blob/master/nussl/datasets/hooks.py
#MixtrueSourceFolder class

stft_params = nussl.STFTParams(window_length=256, hop_length=64)
tfm = nussl.datasets.transforms.Compose([
    #I took out nussl.datasets.transforms.PhaseSensitiveSpectrumApproximation()
    nussl.datasets.transforms.MagnitudeWeights(),
    nussl.datasets.transforms.ToSeparationModel()
])

class COSINEDataSet(nussl.datasets.BaseDataset):
    def __init__(self, folder, mix_folder='mix', source_folders=None, sample_rate=None,
                 ext=None, make_mix=False, **kwargs):
        # 36,000 items in this dataset I will only use 10 for right now
        #I am assuming it pulls the same 10 everytime I run this program
        self.mix_folder = mix_folder
        self.source_folders = source_folders
        self.ext = ['.wav', '.flac', '.mp3'] if ext is None else ext
        self.make_mix = make_mix
        super().__init__(folder, **kwargs)

    def get_items(self, folder):
        if self.source_folders is None:
            self.source_folders = sorted([
                f for f in os.listdir(folder)
                if os.path.isdir(os.path.join(folder, f))
                and f != self.mix_folder
            ])

        if self.make_mix:
            mix_folder = os.path.join(folder, self.source_folders[0])
        else:
            mix_folder = os.path.join(folder, self.mix_folder)
        items = sorted([
            x for x in os.listdir(mix_folder)
            if os.path.splitext(x)[1] in self.ext
        ])
        return items

    def get_mix_and_sources(self, item):
        sources = {}
        for k in self.source_folders:
            source_path = os.path.join(self.folder, k, item)
            if os.path.exists(source_path):
                sources[k] = self._load_audio_file(source_path)
        
        if self.make_mix:
            mix = sum(list(sources.values()))
        else:
            mix_path = os.path.join(self.folder, self.mix_folder, item)
            mix = self._load_audio_file(mix_path)
        return mix, sources

    def process_item(self, item):
        mix, sources = self.get_mix_and_sources(item)
        output = {
            'mix': mix,
            'sources': sources,
            'metadata': {
                'labels': self.source_folders
            }
        }
        return output


items = COSINEDataSet("C:/Users/Jude/Research/",
                      mix_folder='',
                      stft_params=stft_params,
                      transform=tfm)

# define the building blocks
num_features = 129  # number of frequency bins in STFT
num_sources = 2  # how many sources to estimate
mask_activation = 'sigmoid'  # activation function for masks
num_audio_channels = 1  # number of audio channels
modules = {
    'mix_magnitude': {},
    'my_log_spec': {
        'class': 'AmplitudeToDB'
    },
    'my_norm': {
        'class': 'BatchNorm',
    },
    'my_mask': {
        'class': 'Embedding',
        'args': {
            'num_features': num_features,
            'hidden_size': num_features,
            'embedding_size': num_sources,
            'activation': mask_activation,
            'num_audio_channels': num_audio_channels,
            'dim_to_embed': [2, 3]  # embed the frequency dimension (2) for all audio channels (3)
        }
    },
    'my_estimates': {
        'class': 'STFT',
    },
}

connections = [
    ['my_log_spec',    ['mix_magnitude',          ]],
    ['my_norm',        ['my_log_spec',            ]],
    ['my_mask',        ['my_norm',                ]],
    ['my_estimates',   ['my_mask', 'mix_magnitude']]
]

output = ['my_estimates', 'my_mask']

config = {
    'modules': modules,
    'connections': connections,
    'output': output
}

model = nussl.ml.SeparationModel(config)
output = model(items) #This is there the error occurs `

**Comment by jgussman** [comment] 2020-08-04 18:49
[AsipreDataSetClass.pdf](https://github.com/nussl/nussl/files/5023932/AsipreDataSetClass.pdf)

Here is probably a better version.

**Comment by ethman** [comment] 2020-08-04 18:50
Ah, it looks like you're passing the whole dataset to the model, not an item _from_ the dataset into your model. You can check this by printing out `items` in your notebook.

See block [21] in the linked notebook for the subtle difference:

sine_wave_dataset = SineWaves(
    folder, sample_rate=8000, stft_params=stft_params,
    transform=tfm
)

# Let's inspect the 0th item from the dataset
item = sine_wave_dataset[0]  # <-- this is the 0th item from the dataset, not the dataset object itself
item.keys()

**Comment by ethman** [comment] 2020-08-04 18:52
So looking through your notebook, you want to input `items[1]` into the model, not `items`.

**Comment by ethman** [comment] 2020-08-04 18:52
I closed this, but let us know if you have any more questions!

**Closed** 2020-08-04 18:53 UTC
